const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
require('dotenv').config()
const app = express()
app.use(cors())
app.use(express.json())
app.use('/api/student', require('./routes/student'))
app.use('/api/results', require('./routes/results'))
app.use('/api/streak',  require('./routes/streak'))
app.get('/', (req,res) => res.json({status:'StudyTrack API running'}))
mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log('MongoDB connected'))
  .catch(err => console.log('MongoDB error:', err.message))
const PORT = process.env.PORT || 5002
app.listen(PORT, () => console.log(`Server running on http://localhost:${PORT}`))
